line-length = 120
src = ["*/src"]

[lint]
select = ["ALL"]
ignore = [
    "COM812", # Conflicts with ruff formatter
    "D401", # Imperative Docstrings
    "G004", # f-string logging
    "S602", # Allow shell-execution
    "S603", # Check-call subprocess
    "S607", # Starting a process with a partial executable path
]

# Use google pydocstyle convention for docstring style
# Ignore assertions in test files
per-file-ignores = { "tests/**" = ["S101", "PLR2004", "SLF001"]}
pydocstyle.convention = "google"
